services:
  db:
    image: postgres:15
    container_name: pedidos_db
    restart: always
    environment:
      POSTGRES_DB: pedidosdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pedidos_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/pedidosdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      APP_JWT_SECRET: U2VjdXJlS2V5Rm9ySldUU2lnbmluZ1B1cnBvc2VzT25seQ==
      APP_JWT_EXPIRATION_MS: 86400000
    ports:
      - "8080:8080"
    restart: always

volumes:
  postgres_data: